import { CategoryFilter, FilterFunctionType } from '@/app/kategori/utils/kategori-types'

export const categoryFilters: CategoryFilter[] = [
  {
    identifier: 'Setebredde',
    fieldLabel: 'Setebredde',
    searchParamName: 'Setebredde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [
      { fromField: 'setebreddeMinCM', toField: 'setebreddeMaksCM' },
      { fromField: 'setebreddeCM', toField: 'setebreddeCM' },
    ],
    unit: 'cm',
  },
  {
    identifier: 'Setedybde',
    fieldLabel: 'Setedybde',
    searchParamName: 'Setedybde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [
      { fromField: 'setedybdeMinCM', toField: 'setedybdeMaksCM' },
      { fromField: 'setedybdeCM', toField: 'setedybdeCM' },
    ],
    unit: 'cm',
  },
  {
    identifier: 'Setehøyde',
    fieldLabel: 'Setehøyde',
    searchParamName: 'Setehoyde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [
      { fromField: 'setehoydeMinCM', toField: 'setehoydeMaksCM' },
      { fromField: 'setehoydeCM', toField: 'setehoydeCM' },
    ],
    unit: 'cm',
  },
  {
    identifier: 'Brukervekt maks',
    fieldLabel: 'Brukervekt maks',
    searchParamName: 'BrukervektMaks',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'brukervektMaksKG', toField: 'brukervektMaksKG' }],
    unit: 'kg',
  },
  {
    identifier: 'Innendørs bruk',
    fieldLabel: 'Innendørs bruk',
    searchParamName: 'InnendorsBruk',
    filterFunctionType: FilterFunctionType.singleField,
    openSearchFieldGroups: ['innendorsBruk'],
  },
  {
    identifier: 'Utendørs bruk',
    fieldLabel: 'Utendørs bruk',
    searchParamName: 'UtendorsBruk',
    filterFunctionType: FilterFunctionType.singleField,
    openSearchFieldGroups: ['utendorsBruk'],
  },
  {
    identifier: 'Rammetype',
    fieldLabel: 'Rammetype',
    searchParamName: 'rammetype',
    filterFunctionType: FilterFunctionType.singleField,
    openSearchFieldGroups: ['rammetype'],
  },
  {
    identifier: 'Totallengde',
    fieldLabel: 'Totallengde',
    searchParamName: 'Totallengde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'totallengdeCM', toField: 'totallengdeCM' }],
    unit: 'cm',
  },
  {
    identifier: 'Totalbredde',
    fieldLabel: 'Totalbredde',
    searchParamName: 'Totalbredde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'totalbreddeCM', toField: 'totalbreddeCM' }],
    unit: 'cm',
  },
  {
    identifier: 'Madrassbredde',
    fieldLabel: 'Madrassbredde',
    searchParamName: 'Madrassbredde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [
      { fromField: 'madrassbreddeMinCM', toField: 'madrassbreddeMaksCM' },
      { fromField: 'madrassbreddeCM', toField: 'madrassbreddeCM' },
    ],
    unit: 'cm',
  },
  {
    identifier: 'Madrasslengde',
    fieldLabel: 'Madrasslengde',
    searchParamName: 'Madrasslengde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [
      { fromField: 'madrasslengdeMinCM', toField: 'madrasslengdeMaksCM' },
      { fromField: 'madrasslengdeCM', toField: 'madrasslengdeCM' },
    ],
    unit: 'cm',
  },
  {
    identifier: 'Skrittlengde',
    fieldLabel: 'Skrittlengde',
    searchParamName: 'Skrittlengde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'skrittlengdeMinCM', toField: 'skrittlengdeMaksCM' }],
    unit: 'cm',
  },
  {
    identifier: 'Bredde',
    fieldLabel: 'Bredde',
    searchParamName: 'Bredde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'breddeCM', toField: 'breddeCM' }],
    unit: 'cm',
  },
  {
    identifier: 'Lengde',
    fieldLabel: 'Lengde',
    searchParamName: 'Lengde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'lengdeCM', toField: 'lengdeCM' }],
    unit: 'cm',
  },
  {
    identifier: 'Dybde',
    fieldLabel: 'Dybde',
    searchParamName: 'Dybde',
    filterFunctionType: FilterFunctionType.range,
    openSearchFieldGroups: [{ fromField: 'dybdeCM', toField: 'dybdeCM' }],
    unit: 'cm',
  },
]
