version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:15"
    groups:
      Minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    registries:
      - npm-github
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
