apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
  name: hm-oversikt-frontend
  namespace: teamdigihot
spec:
  image: { { image } }
  port: 3000
  ingresses:
    - https://hjelpemiddeloversikt.dev.nav.no
