apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://finnhjelpemiddel.nav.no'
    - 'https://finnhjelpemiddel.ansatt.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-grunndata-alternativprodukter
        - application: hm-grunndata-db
        - application: hm-finnhjelpemiddel-bff
  env:
    - name: RUNTIME_ENVIRONMENT
      value: prod
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/server/app/no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "a6d5a807-6173-4654-9317-8b196cccef5d"
    sidecar:
      enabled: true
