apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://finnhjelpemiddel.nav.no'
  accessPolicy:
    outbound:
      external:
        - host: hm-oebs-api-proxy.prod-fss-pub.nais.io
      rules:
        - application: hm-grunndata-search
  env:
    - name: RUNTIME_ENVIRONMENT
      value: prod
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/server/app/no
