apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://hjelpemiddeloversikt.dev.nav.no'
  accessPolicy:
  outbound:
    rules:
      - application: hm-grunndata-search
  env:
    - name: RUNTIME_ENVIRONMENT
      value: dev
