apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/hjelpemidler/finnhjelpemidler'
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
  env:
    - name: RUNTIME_ENVIRONMENT
      value: prod
