apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://finnhjelpemiddel.intern.dev.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
      external:
        - host: teamdigihot-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: hm-oversikt-frontend-unleash-secrets
  env:
    - name: RUNTIME_ENVIRONMENT
      value: dev
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamdigihot-unleash-api.nav.cloud.nais.io/api'

