apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend-alpha
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://finnhjelpemidler-alpha.intern.dev.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
  env:
    - name: RUNTIME_ENVIRONMENT
      value: dev
