apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oversikt-frontend
  namespace: teamdigihot
  labels:
    app: hm-oversikt-frontend
    team: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://finnhjelpemiddel.intern.dev.nav.no'
    - 'https://finnhjelpemiddel.ansatt.dev.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-grunndata-alternativprodukter
  env:
    - name: RUNTIME_ENVIRONMENT
      value: dev
    - name: BUILD_ENV
      value: dev
    - name: IMAGE_PROXY_URL
      value: https://finnhjelpemiddel.intern.dev.nav.no/imageproxy
    - name: CDN_URL
      value: https://finnhjelpemiddel.intern.dev.nav.no/imageproxy/file/
    - name: FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: HM_SEARCH_URL
      value: http://hm-grunndata-search
    - name: ASSET_PREFIX
      value: https://cdn.nav.no/teamdigihot/hm-oversikt-frontend/prod
    - name: HM_GRUNNDATA_ALTERNATIVPRODUKTER_URL
      value: http://hm-grunndata-alternativprodukter
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/server/app/no

