import { Product } from './product-util'

export const sparePartMockResponse: Product[] = [
  {
    id: '1R',
    title: 'Aktuator stol 2',
    attributes: {},
    applicableAgreementInfo: null,
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: "'2 Aktuator stol arbeid Wombat Living el str1/2 200N '",
    accessory: false,
    sparepart: true,
    photos: [{ uri: '/400d/orig/20537.jpg' }],
    documents: [],
    supplierId: '312222133',
  },
  {
    id: '2R',
    title: 'Aktuator skinne 2',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText:
      '2 Aktuator stol arbeid Wombat Living el str1/2 200N, 2 Aktuator stol arbeid Wombat Living el str1/2 200N ',
    accessory: false,
    sparepart: true,
    photos: [{ uri: '/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222155',
  },
  {
    id: '3R',
    title: 'Aktuator dusj 4',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: '2 Aktuator stol, 2 Aktuator stol arbeid Wombat Living el str1/2 200N',
    accessory: false,
    sparepart: true,
    photos: [{ uri: '/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222188',
  },
  {
    id: '1R',
    title: 'Aktuator stol 2',
    attributes: {},
    applicableAgreementInfo: null,
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: "'2 Aktuator stol arbeid Wombat Living el str1/2 200N '",
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222133',
  },
  {
    id: '2R',
    title: 'Aktuator skinne 2',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText:
      '2 Aktuator stol arbeid Wombat Living el str1/2 200N, 2 Aktuator stol arbeid Wombat Living el str1/2 200N ',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222155',
  },
  {
    id: '3R',
    title: 'Aktuator dusj 4',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: '2 Aktuator stol, 2 Aktuator stol arbeid Wombat Living el str1/2 200N',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222188',
  },
]

export const accessoryMockResponse: Product[] = [
  {
    id: '1A',
    title: 'Aktuator Accessory',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: "'2 Aktuator stol arbeid Wombat Living el str1/2 200N '",
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222133',
  },
  {
    id: '2A',
    title: 'Accessory skinne 2',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText:
      '2 Aktuator stol arbeid Wombat Living el str1/2 200N, 2 Aktuator stol arbeid Wombat Living el str1/2 200N ',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222155',
  },
  {
    id: '3A',
    title: 'Accessory dusj 4',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: '2 Aktuator stol, 2 Aktuator stol arbeid Wombat Living el str1/2 200N',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222188',
  },
  {
    id: '1A',
    title: 'Aktuator Accessory',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: "'2 Aktuator stol arbeid Wombat Living el str1/2 200N '",
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222133',
  },
  {
    id: '2A',
    title: 'Accessory skinne 2',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText:
      '2 Aktuator stol arbeid Wombat Living el str1/2 200N, 2 Aktuator stol arbeid Wombat Living el str1/2 200N ',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222155',
  },
  {
    id: '3A',
    title: 'Accessory dusj 4',
    attributes: {},
    applicableAgreementInfo: {
      id: '',
      identifier: '',
      rank: 1,
      postNr: 2,
      postIdentifier: '',
      postTitle: 'string',
    },
    variantCount: 1,
    variants: [],
    compareData: {
      techDataRange: {},
      agreementRank: 0,
    },
    isoCategory: '',
    isoCategoryTitle: '',
    isoCategoryText: '2 Aktuator stol, 2 Aktuator stol arbeid Wombat Living el str1/2 200N',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'https://finnhjelpemidler.intern.dev.nav.no/imageproxy/1600d/orig/64813.jpg' }],
    documents: [],
    supplierId: '312222188',
  },
]
