import { Product } from './product-util'

export const accessoriesMock: Product[] = [
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: true,
    sparepart: false,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
]

export const sparePartsMock: Product[] = [
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
  {
    id: 'HMDB-52674',
    title: 'Univox CLS-5',
    attributes: {
      matchingProducts: ['HMDB-64818', 'HMDB-54382', 'HMDB-50757'],
      series: 'Univox CLS-5',
      shortdescription:
        'Digital lydinngang. Automatic gain control. Justerbar tidsforsinkelse for tilkoblet lyd. Dekningsgrad i et tilnærmet kvadratisk rom er 140 kvm. ',
      text: 'Teleslyngeforsterker egnet til bruk i private hjem, spesielt tilpasset TV og radio, slik at man trådløst kan høre via telespolen i høreapparatet. Har analoge og digitale tilkoblinger og TV-sync for lyd uten ekko.   ',
      bestillingsordning: false,
      commonCharacteristics: {},
    },
    applicableAgreementInfo: {
      id: '9d8ff31e-c536-4f4d-9b2f-75cc527c727f',
      identifier: 'HMDB-8654',
      title: 'Hørselshjelpemidler',
      postIdentifier: 'HMDB-1111',
      postNr: 4,
      postTitle: 'Teleslyngeforsterker',
      rank: 1,
      expired: '',
    },
    variantCount: 1,
    variants: [
      {
        id: '64e4f716-08bb-4b48-8a52-695511496183',
        hmsArtNr: '202258',
        supplierRef: '1104113',
        articleName: 'Univox CLS-5',
        techData: {},
        hasAgreement: true,
        agreementInfo: null,
        filters: {},
        expired: '2043-08-07T14:33:40.468028091',
      },
    ],
    compareData: { techDataRange: {}, agreementRank: null },
    isoCategory: '22183001',
    isoCategoryTitle: 'Teleslyngeforsterkere',
    isoCategoryText:
      'Hjelpemidler for å ta imot eller sende informasjon med elektromagnetiske bølger i teleslyngesystemer. Hørselshjelpemidler, se 22 06.',
    accessory: false,
    sparepart: true,
    photos: [{ uri: 'orig/52674.jpg' }],
    documents: [],
    supplierId: 'e9e27708-16be-4995-83a7-f857b77d0913',
  },
]
